
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ATMOST = 12;
  public static final int EQUALS = 13;
  public static final int LPAREN = 20;
  public static final int GREATER = 18;
  public static final int SEMI = 26;
  public static final int LESS = 19;
  public static final int MINUS = 30;
  public static final int RPAREN = 21;
  public static final int NOT = 16;
  public static final int AND = 14;
  public static final int OR = 15;
  public static final int COMMA = 25;
  public static final int TYPECASE = 10;
  public static final int CLASS = 2;
  public static final int DIV = 28;
  public static final int PLUS = 29;
  public static final int IF = 5;
  public static final int DOT = 31;
  public static final int EOF = 0;
  public static final int RETURN = 9;
  public static final int error = 1;
  public static final int ATLEAST = 11;
  public static final int IDENT = 34;
  public static final int TIMES = 27;
  public static final int COLON = 24;
  public static final int NEG = 32;
  public static final int LBRACE = 22;
  public static final int ELSE = 7;
  public static final int WHILE = 8;
  public static final int RBRACE = 23;
  public static final int EXTENDS = 4;
  public static final int DEF = 3;
  public static final int GETS = 17;
  public static final int STRING_LIT = 33;
  public static final int INT_LIT = 35;
  public static final int ELIF = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CLASS",
  "DEF",
  "EXTENDS",
  "IF",
  "ELIF",
  "ELSE",
  "WHILE",
  "RETURN",
  "TYPECASE",
  "ATLEAST",
  "ATMOST",
  "EQUALS",
  "AND",
  "OR",
  "NOT",
  "GETS",
  "GREATER",
  "LESS",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "COLON",
  "COMMA",
  "SEMI",
  "TIMES",
  "DIV",
  "PLUS",
  "MINUS",
  "DOT",
  "NEG",
  "STRING_LIT",
  "IDENT",
  "INT_LIT"
  };
}

